// Generated by CoffeeScript 1.10.0
(function() {
  window.CanonicalXML = (function() {
    CanonicalXML.prototype.RawXML = "";

    CanonicalXML.prototype.CanonXML = "";

    CanonicalXML.prototype.CanonicalisationMethod = "http://www.w3.org/TR/2001/REC-xml-c14n-20010315";


    /*
    Erzeugt ein Neues Caninicalisiertes XML document
     */

    function CanonicalXML(RawXML, Algorithm) {
      var can;
      this.RawXML = RawXML;

      /*
      can = new Canonicalisation_Module_Incl
      namespaces = {inclusiveNamespacesPrefixList:"ds"}
      @CanonXML = can.createCanonicaliser("http://www.w3.org/TR/2001/REC-xml-c14n-20010315").canonicalise(@RawXML,namespaces)
      #@CanonXML=@CanonXML.replace(/>\s*</g,"><")
      #@CanonicalXML = $.parseXML(@CanonicalXML)
       */
      can = new Canonicalisation_Module.ExclusiveCanonicalizationWithComments;
      this.CanonXML = can.process(this.RawXML);
      this.CanonicalisationMethod = can.getAlgorithmName();
    }

    return CanonicalXML;

  })();

}).call(this);
